/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoagenda;

import javax.swing.JOptionPane;
import static projetoagenda.GerenciadorContato.listaContatos;
import static projetoagenda.GerenciadorContato.listaParametro;

/**
 *
 * @author solanje
 */
public class TelaInicialAgenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicialAgenda
     */
    public TelaInicialAgenda() {
        initComponents();
        setResizable(false);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setTitle("Agenda de Contatos");
        
        // arquivação e salvamento das informações
        arquivoContatos();
        arquivoContatosExcluidos();
        arquivoContatosParametro();
    }
    
    public void arquivoContatos(){
        if (BancoDeDados.lerArquivoContatos() == null){
            BancoDeDados.salvarContatos(GerenciadorContato.listaContatos);
            System.out.println("criar");
        } else {
            GerenciadorContato.listaContatos = BancoDeDados.lerArquivoContatos();
            System.out.println("salvar");
        }
    }
    
    public void arquivoContatosExcluidos(){
        if (BancoDeDados.lerArquivoContatosExcluidos() == null){
            BancoDeDados.salvarContatosExcluidos(GerenciadorContato.listaContatosExcluidos);
            System.out.println("criar");
        } else {
            GerenciadorContato.listaContatosExcluidos = BancoDeDados.lerArquivoContatosExcluidos();
            System.out.println("salvar");
        }
    }
    
    public void arquivoContatosParametro(){
        if (BancoDeDados.lerArquivoContatosParametro() == null){
            BancoDeDados.salvarContatosParametro(GerenciadorContato.listaParametro);
            System.out.println("criar");
        } else {
            GerenciadorContato.listaParametro = BancoDeDados.lerArquivoContatosParametro();
            System.out.println("salvar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contatosButton = new javax.swing.JButton();
        agendaLogoLabel = new javax.swing.JLabel();
        agendaLabel = new javax.swing.JLabel();
        favoritosButton = new javax.swing.JButton();
        adicionarButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        contatosButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        lixeiraMenu = new javax.swing.JMenu();
        contatosMenuItem = new javax.swing.JMenuItem();
        esvaziarMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        sobreMenu = new javax.swing.JMenu();
        desenvolvedorMenuItem = new javax.swing.JMenuItem();
        programaMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        contatosButton.setBackground(new java.awt.Color(0, 204, 102));
        contatosButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        contatosButton.setForeground(new java.awt.Color(255, 255, 255));
        contatosButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\solanje\\Documents\\Sadrak\\ícones\\Sem título-2.png")); // NOI18N
        contatosButton.setText("Todos os Contatos");
        contatosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contatosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contatosButtonActionPerformed(evt);
            }
        });

        agendaLogoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\solanje\\Documents\\Sadrak\\ícones\\Sem título-1.png")); // NOI18N
        agendaLogoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        agendaLabel.setBackground(new java.awt.Color(255, 255, 255));
        agendaLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        agendaLabel.setForeground(new java.awt.Color(0, 153, 255));
        agendaLabel.setText("Agenda");
        agendaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        favoritosButton.setBackground(new java.awt.Color(255, 51, 51));
        favoritosButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        favoritosButton.setForeground(new java.awt.Color(255, 255, 255));
        favoritosButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\solanje\\Documents\\Sadrak\\ícones\\icone-4.png")); // NOI18N
        favoritosButton.setText("Remover");
        favoritosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        favoritosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoritosButtonActionPerformed(evt);
            }
        });

        adicionarButton.setBackground(new java.awt.Color(255, 153, 0));
        adicionarButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adicionarButton.setForeground(new java.awt.Color(255, 255, 255));
        adicionarButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\solanje\\Documents\\Sadrak\\ícones\\Sem título-4.png")); // NOI18N
        adicionarButton.setText("Adicionar");
        adicionarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adicionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sair");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        contatosButton1.setBackground(new java.awt.Color(204, 0, 204));
        contatosButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        contatosButton1.setForeground(new java.awt.Color(255, 255, 255));
        contatosButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\solanje\\Documents\\Sadrak\\ícones\\icone-2.png")); // NOI18N
        contatosButton1.setText("Pesquisar Contatos");
        contatosButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contatosButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contatosButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(agendaLabel)
                    .addComponent(agendaLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 164, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(adicionarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contatosButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .addComponent(favoritosButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contatosButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agendaLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agendaLabel)
                .addGap(18, 18, 18)
                .addComponent(contatosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contatosButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(favoritosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adicionarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 255));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setRequestFocusEnabled(false);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\solanje\\Documents\\Sadrak\\ícones\\Sem título-17.png")); // NOI18N
        jMenu1.setText("Atualizar contato");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Atualizar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        lixeiraMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\solanje\\Documents\\Sadrak\\ícones\\icone-6.png")); // NOI18N
        lixeiraMenu.setText("Lixeira");

        contatosMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        contatosMenuItem.setText("Ver contatos excluídos");
        contatosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contatosMenuItemActionPerformed(evt);
            }
        });
        lixeiraMenu.add(contatosMenuItem);

        esvaziarMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        esvaziarMenuItem.setText("Esvaziar lixeira");
        esvaziarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esvaziarMenuItemActionPerformed(evt);
            }
        });
        lixeiraMenu.add(esvaziarMenuItem);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Recuperar contatos excluídos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        lixeiraMenu.add(jMenuItem1);

        jMenuBar1.add(lixeiraMenu);

        sobreMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\solanje\\Documents\\Sadrak\\ícones\\icone-5.png")); // NOI18N
        sobreMenu.setText("Sobre");

        desenvolvedorMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        desenvolvedorMenuItem.setText("Desenvolvedor");
        desenvolvedorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desenvolvedorMenuItemActionPerformed(evt);
            }
        });
        sobreMenu.add(desenvolvedorMenuItem);

        programaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        programaMenuItem.setText("Programa");
        programaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programaMenuItemActionPerformed(evt);
            }
        });
        sobreMenu.add(programaMenuItem);

        jMenuBar1.add(sobreMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void favoritosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favoritosButtonActionPerformed
        if (listaContatos.size() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum contato salvo.");
        } else {
            new TelaRemoverContato().setVisible(true);
        }
    }//GEN-LAST:event_favoritosButtonActionPerformed

    private void contatosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contatosButtonActionPerformed
        if (listaContatos.size() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum contato salvo.");
        } else {
            new TelaListaContatos().setVisible(true);
        }
    }//GEN-LAST:event_contatosButtonActionPerformed

    private void adicionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarButtonActionPerformed
        new TelaAdicionarContato().setVisible(true);
    }//GEN-LAST:event_adicionarButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja, realmente, encerrar a aplicação?");
        if (opcao == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void contatosButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contatosButton1ActionPerformed
        if (listaContatos.size() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum contato salvo.");
        } else {
            new TelaPesquisarContato().setVisible(true);
        }
    }//GEN-LAST:event_contatosButton1ActionPerformed

    private void desenvolvedorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desenvolvedorMenuItemActionPerformed
        new TelaDesenvolvedor().setVisible(true);
    }//GEN-LAST:event_desenvolvedorMenuItemActionPerformed

    private void programaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programaMenuItemActionPerformed
        new TelaPrograma().setVisible(true);
    }//GEN-LAST:event_programaMenuItemActionPerformed

    private void esvaziarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esvaziarMenuItemActionPerformed
        if (GerenciadorContato.listaContatosExcluidos.size() == 0) {
            JOptionPane.showMessageDialog(null, "Lixeira já está vazia.");
        } else {
            int opcao = JOptionPane.showConfirmDialog(null, "Remover permanentemente os contatos excluídos?");
            if (opcao == 0) {
                boolean resultado = GerenciadorContato.listaContatosExcluidos.removeAll(listaParametro);
                if (resultado) {
                    JOptionPane.showMessageDialog(null, "Lixeira esvaziada.");
                }
            }
        }
        
        BancoDeDados.salvarContatosExcluidos(GerenciadorContato.listaContatosExcluidos);
    }//GEN-LAST:event_esvaziarMenuItemActionPerformed

    private void contatosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contatosMenuItemActionPerformed
        if (GerenciadorContato.listaContatosExcluidos.size() == 0){
           JOptionPane.showMessageDialog(null, "Lixeira vazia."); 
        } else {
            new TelaListaContatosExcluidos().setVisible(true);
        }
    }//GEN-LAST:event_contatosMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (GerenciadorContato.listaContatosExcluidos.size() == 0){
           JOptionPane.showMessageDialog(null, "Lixeira vazia."); 
        } else {
            new TelaRecuperarContato().setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (GerenciadorContato.listaContatos.size() == 0){
           JOptionPane.showMessageDialog(null, "Nenhum contato salvo."); 
        } else {
            new TelaAtualizarContato().setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (" ".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarButton;
    private javax.swing.JLabel agendaLabel;
    private javax.swing.JLabel agendaLogoLabel;
    private javax.swing.JButton contatosButton;
    private javax.swing.JButton contatosButton1;
    private javax.swing.JMenuItem contatosMenuItem;
    private javax.swing.JMenuItem desenvolvedorMenuItem;
    private javax.swing.JMenuItem esvaziarMenuItem;
    private javax.swing.JButton favoritosButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu lixeiraMenu;
    private javax.swing.JMenuItem programaMenuItem;
    private javax.swing.JMenu sobreMenu;
    // End of variables declaration//GEN-END:variables
}
